{% set name = "guietta" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 069f2ed21cd9d2e50e8856c84a025a3b9f8141c4d70949961c402b7780f7db17

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - setuptools
    - pip
  run:
    - python >=3.5
    - pyside2

# Test is done in run_test.sh, because we need to start a
# virtual framebuffer or the PySide2/PyQt imports will fail.
about:
  home: https://github.com/alfiopuglisi/guietta
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Simple GUI builder for Python
  description: |
    guietta is a tool to quickly create simple GUIs,
    built on top of QT.
  doc_url: https://guietta.readthedocs.io/
  dev_url: https://github.com/alfiopuglisi/guietta

extra:
  recipe-maintainers:
    - alfiopuglisi
